//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chirst_Temple_Kid_Finder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeTable
    {
        public int Id { get; set; }
        public string ChildCode { get; set; }
        public string Room_Number { get; set; }
    }
}
