//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Chirst_Temple_Kid_Finder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeAssignTable
    {

        public int Id { get; set; }
        [Required]
        [EmailAddress]
        public string Email { get; set; }
        [Required]
        [StringLength(5), MinLength(5)]
        [Display(Name = "Child Code")]
        public string ChildCode { get; set; }
    }
}
