//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chirst_Temple_Kid_Finder.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbcaa9cff9bf624b1ebcf9a8120126a40eEntities3 : DbContext
    {
        public dbcaa9cff9bf624b1ebcf9a8120126a40eEntities3()
            : base("name=dbcaa9cff9bf624b1ebcf9a8120126a40eEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CodeAssignTable> CodeAssignTables { get; set; }
        public virtual DbSet<CodeTable> CodeTables { get; set; }
    }
}
